name: LicenseManager
api-version: 1.16
authors:
  - AsMax
main: me.asmax.licensemanager.LicenseManager
version: @version@

commands:
   installkey:
   key:
   setservername:
   servername:
   forward:
   validate:
   togglenotifications:
   activatelite: